version: '2'
services:
  app:
    build: .
    ports:
    - "3000:3000"
    volumes:
    - .:/app
    links:
    - mongo
  mongo:
    image: mongo
    ports:
    - "27017:27017"
    volumes:
    - ./db:/var/lib/mongodb
    restart: always