version: '2'
services:
  app:
    build: .
    environment:
    - DEBUG=ff:*
    links:
    - mongo
    volumes:
    - ./public/images/carousel:/app/public/images/carousel
    - ./public/images/products:/app/public/images/products
  mongo-seed:
    build: ./mongo-seed
    links:
    - mongo
  mongo:
    image: mongo
    ports:
    - "27017:27017"
    volumes:
    - ./db:/data/db