version: '2'
services:
  app:
    build: .
    environment:
    - DEBUG=ff:*
    links:
    - mongo
  mongo-seed:
    build: ./mongo-seed
    links:
    - mongo
  mongo-express:
    image: mongo-express
    ports:
    - "8081:8081"
    links:
    - mongo
  mongo:
    image: mongo
    ports:
    - "27017:27017"
    volumes:
    - ./db:/data/db