version: '2'
services:
  app:
    build: .
    links:
    - mongo
  mongo-express:
    image: mongo-express
    ports:
    - "8081:8081"
  mongo:
    image: mongo
    ports:
    - "27017:27017"
    volumes:
    - ./db:/data/db