version: '2'
services:
  app:
    ports:
    - "3001:3000"
    volumes:
    - .:/app
    command: npm run server
  mongo-express:
    image: mongo-express
    ports:
    - "8081:8081"
    links:
    - mongo